books_library/authors/urls.py
from django.conf.urls import url

from books_library.authors.views import AuthorCreateView, AuthorListView, \
    AuthorDetailView, AuthorUpdateView, AuthorDeleteView

urlpatterns = [
    url('^$', AuthorListView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', AuthorDetailView.as_view(), name='detail'),
    url('^create/$', AuthorCreateView.as_view(), name='create'),
    url('^(?P<pk>\d+)/delete/$', AuthorDeleteView.as_view(), name='delete'),
    url('^(?P<pk>\d+)/edit/$', AuthorUpdateView.as_view(), name='edit'),
]

books_library/books/urls.py
from django.conf.urls import url

from books_library.books.views import BookCreateView, BookListView, BookDetailView, \
    BookUpdateView, BookDeleteView, search

urlpatterns = [
    url('^$', BookListView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', BookDetailView.as_view(), name='detail'),
    url('^create/$', BookCreateView.as_view(), name='create'),
    url('^(?P<pk>\d+)/delete/$', BookDeleteView.as_view(), name='delete'),
    url('^(?P<pk>\d+)/edit/$', BookUpdateView.as_view(), name='edit'),
    url(r'^search/', search, name='search'),
]

books_library/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import login, logout
from django.contrib.auth.decorators import user_passes_test
from django.views.generic import TemplateView

from books_library.common.views import RegisterFormView, LoginFormView

login_forbidden = user_passes_test(lambda u: u.is_anonymous(), '/books/', '')
urlpatterns = [
    # url(r'^$', TemplateView.as_view(template_name='base.html')),
    url(r'^admin/', admin.site.urls),
    url(r'^register/$', login_forbidden(RegisterFormView.as_view()), name="signup"),
    url(r'^login/$', login_forbidden(LoginFormView.as_view()),  name="login"),
    url(r'^logout/$', logout, name='logout', kwargs={'next_page': '/books/'}),
    url(r'^books/', include('books_library.books.urls', namespace='books')),
    url(r'^authors/', include('books_library.authors.urls', namespace='authors')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books_library/authors/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.translation import ugettext_lazy as _


class Author(models.Model):
    first_name = models.CharField(_('first name'), max_length=30)
    last_name = models.CharField(_('last name'), max_length=30)

    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        full_name = '{} {}'.format(self.first_name, self.last_name)
        return full_name.strip()

    def __unicode__(self):
        return '{} {}'.format(self.first_name, self.last_name)

books_library/books/models.py
from __future__ import unicode_literals

from django.db import models


class Book(models.Model):
    authors = models.ManyToManyField('authors.Author')
    title = models.CharField(max_length=100)
    description = models.TextField()

    def get_authors(self):
        return ', '.join(str(author) for author in self.authors.all())

    def __unicode__(self):
        return self.title

books_library/common/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

books_library/authors/forms.py
from django import forms

from books_library.authors.models import Author
from books_library.common.forms import BootstrapMixin


class AuthorCreationForm(BootstrapMixin, forms.ModelForm):
    class Meta:
        model = Author
        fields = ('first_name', 'last_name')

books_library/books/forms.py
from django import forms

from books_library.books.models import Book
from books_library.common.forms import BootstrapMixin


class BookCreationForm(BootstrapMixin, forms.ModelForm):
    class Meta:
        model = Book
        fields = ('authors', 'title', 'description')

books_library/common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class BootstrapMixin(object):
    def __init__(self, *args, **kwargs):
        super(BootstrapMixin, self).__init__(*args, **kwargs)
        meta = getattr(self, 'Meta', object)
        bootstrap_exclude = getattr(meta, 'bootstrap_exclude', [])
        for field in self.fields:
            if field not in bootstrap_exclude:
                if self.fields[field].widget.__class__ not in [forms.CheckboxInput, forms.RadioSelect, forms.FileInput, forms.ClearableFileInput]:
                    cls = self.fields[field].widget.attrs.get('class', '')
                    cls += ' form-control'
                    self.fields[field].widget.attrs['class'] = cls
            self.fields[field].widget.attrs['placeholder'] = self.fields[field].label or field.capitalize()


class CustomUserCreationForm(BootstrapMixin, UserCreationForm):
    msg = 'Letters, digits and @/./+/-/_ only.'
    username = forms.CharField(widget=forms.TextInput(
        attrs={'rows': 5, 'placeholder': msg}))
    email = forms.EmailField(required=True, widget=forms.TextInput(
        attrs={'placeholder': 'example@mail.com'}))

    class Meta:
        model = User
        fields = ('username', 'email')


class CustomUserAuthenticationForm(BootstrapMixin, AuthenticationForm):

    class Meta:
        model = User

books_library/authors/views.py
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView, CreateView, UpdateView
from django.views.generic.list import ListView

from books_library.authors.forms import AuthorCreationForm
from books_library.authors.models import Author
from books_library.common.views import ActiveMenuItemMixin


class AuthorListView(ActiveMenuItemMixin, ListView):
    model = Author
    context_object_name = 'authors'
    template_name = 'authors/list.html'
    active_menu_item = 'authors'


class AuthorDetailView(DetailView):
    model = Author
    template_name = 'authors/detail.html'
    context_object_name = 'author'


class AuthorCreateView(CreateView):
    model = Author
    form_class = AuthorCreationForm
    template_name = 'authors/create.html'
    active_menu_item = 'create_author'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(AuthorCreateView, self).dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('authors:detail', kwargs={'pk': self.object.id})


class AuthorUpdateView(UpdateView):
    model = Author
    form_class = AuthorCreationForm
    template_name = 'authors/create.html'

    def get_success_url(self, **kwargs):
        return reverse('authors:detail', kwargs={'pk': self.object.id})

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(AuthorUpdateView, self).dispatch(request, *args, **kwargs)


class AuthorDeleteView(DeleteView):
    model = Author
    template_name = "authors/confirm_delete.html"
    success_url = reverse_lazy('authors:list')

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(AuthorDeleteView, self).dispatch(request, *args, **kwargs)

books_library/books/views.py
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse, reverse_lazy
from django.http.response import JsonResponse
from django.utils.decorators import method_decorator
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView

from books_library.books.forms import BookCreationForm
from books_library.books.models import Book
from books_library.common.decorators import ajax_required
from books_library.common.views import ActiveMenuItemMixin


class BookListView(ActiveMenuItemMixin, ListView):
    model = Book
    context_object_name = 'books'
    template_name = 'books/list.html'
    active_menu_item = 'books'


class BookDetailView(DetailView):
    model = Book
    template_name = 'books/detail.html'
    context_object_name = 'book'


class BookCreateView(CreateView):
    model = Book
    form_class = BookCreationForm
    template_name = 'books/create.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(BookCreateView, self).dispatch(request, *args, **kwargs)

    def get_success_url(self, **kwargs):
        return reverse('books:detail', kwargs={'pk': self.object.id})


class BookUpdateView(UpdateView):
    model = Book
    form_class = BookCreationForm
    template_name = 'books/create.html'

    def get_success_url(self, **kwargs):
        return reverse('books:detail', kwargs={'pk': self.object.id})

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(BookUpdateView, self).dispatch(request, *args, **kwargs)


class BookDeleteView(DeleteView):
    model = Book
    template_name = "books/confirm_delete.html"
    success_url = reverse_lazy('books:list')

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(BookDeleteView, self).dispatch(request, *args, **kwargs)


@login_required
@ajax_required
def search(request):
    books = []
    q = request.GET.get('q')
    if q:
        books = Book.objects.filter(title__icontains=q)
    res = [{'id': book.id, 'title': book.title} for book in books]
    return JsonResponse({'result': res})

books_library/common/views.py
from django.contrib.auth import login, authenticate
from django.views.generic.edit import FormView

from books_library.common.forms import CustomUserCreationForm, \
    CustomUserAuthenticationForm


class ActiveMenuItemMixin(object):
    def get_context_data(self, **kwargs):
        ctx = super(ActiveMenuItemMixin, self).get_context_data(**kwargs)
        ctx['active_menu_item'] = getattr(self, 'active_menu_item', None)
        return ctx


class RegisterFormView(ActiveMenuItemMixin, FormView):
    form_class = CustomUserCreationForm
    success_url = '/books/'
    template_name = 'registration/register.html'
    active_menu_item = 'signup'

    def form_valid(self, form):
        form.save()
        user = authenticate(username=form.data['username'],
                            password=form.data['password1'])
        login(self.request, user)
        return super(RegisterFormView, self).form_valid(form)


class LoginFormView(ActiveMenuItemMixin, FormView):
    form_class = CustomUserAuthenticationForm
    success_url = '/books/'
    template_name = 'registration/login.html'
    active_menu_item = 'login'

    def form_valid(self, form):
        user = authenticate(username=form.data['username'],
                            password=form.data['password'])
        login(self.request, user)
        return super(LoginFormView, self).form_valid(form)

books_library/templates/books/confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <div class="book-confirm-delete col-sm-6 col-sm-offset-3">
    <div class="panel panel-default">
      <div class="panel-body">
        <form action="" method="post">{% csrf_token %}
          <p>Are you sure you want to delete "{{ object }}"?</p>
          <div class="buttons pull-right">
            <a href="{% url 'books:detail' object.id %}" class="btn btn-primary">No</a>
            <input class="btn btn-danger" type="submit" value="Yes"/>
          </div>
        </form>
      </div>
    </div>
  </div>

{% endblock %}

books_library/templates/books/create.html
{% extends 'base.html' %}

{% block content %}
  <div class="new-book col-sm-6 col-sm-offset-3">
    <h1>New Book</h1>
    <hr>
    <form class="form-horizontal" method="post">{% csrf_token %}
      <fieldset class="col-sm-12">
        {% for field in form %}
          <div class="form-group  {% if field.errors %} has-error {% endif %}">
            <label class="control-label">{{ field.label }}</label>

            <div class="controls">{{ field }}</div>
            <div class="help-block">
              {{ field.help_text }}
              <strong>
                {{ field.errors }}
              </strong>
            </div>
          </div>
        {% endfor %}
      </fieldset>

      <div class="form-actions">
        <p>
          <button type="submit" class="btn btn-primary btn-block">Submit
          </button>
        </p>
      </div>
    </form>
  </div>

{% endblock %}

books_library/templates/books/detail.html
{% extends 'base.html' %}

{% block content %}
  <div class="book-detail col-sm-6 col-sm-offset-3">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <span>ID: {{ book.id }}</span>
      </div>
      <div class="panel-body">
        <span>Title: {{ book.title }}</span>
        {% if user.is_authenticated %}
          <div class="btn-toolbar pull-right">
            <div class="btn-group">
              <a href="{% url 'books:edit' book.id %}" type="button" class="btn btn-default">
                <i class="glyphicon glyphicon-edit"></i>Edit
              </a>
              <a href="{% url 'books:delete' book.id %}" type="button" class="btn btn-default">Delete</a>
            </div>
          </div>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

books_library/templates/books/list.html
{% extends 'base.html' %}

{% block content %}
  <div class="book-list col-sm-6 col-sm-offset-3">
    <div class="page-header">
      {% if user.is_authenticated %}
        <div class="btn-toolbar pull-right">
          <div class="btn-group">
            <a href="{% url 'books:create' %}" type="button"
               class="btn btn-primary">Create New Book</a>
          </div>
        </div>
      {% endif %}
      <h1>Books</h1>

    </div>
    <div class="list-group">
      {% for book in books %}
        <a class="list-group-item" href="{% url 'books:detail' book.id %}">
          <span>Title: </span>{{ book.title }}
          <br>
          <span>Authors: </span>{{ book.get_authors }}
        </a>
      {% endfor %}
    </div>
  </div>

{% endblock %}